### ISSUE TITLE
PsiFile:AgentJar.class; of class:class com.intellij.psi.impl.compiled.ClsFileImpl; Do not use walking visitor inside compiled PSI since getNextSibling() is too slow there at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:59)

### ISSUE THREAD

**Issue by gitlevich** [intellij-elixir/intellij-elixir#3077]
# System

Plugin Version: 14.0.0
Application: IntelliJ IDEA Ultimate Edition (2022.3.1)
Operating System: Mac OS X (13.1)

# Event

### Stacktrace

<details>

<summary>
java.lang.Throwable: PsiFile:AgentJar.class; of class:class com.intellij.psi.impl.compiled.ClsFileImpl; Do not use walking visitor inside compiled PSI since getNextSibling() is too slow there
</summary>

```
java.lang.Throwable: PsiFile:AgentJar.class; of class:class com.intellij.psi.impl.compiled.ClsFileImpl; Do not use walking visitor inside compiled PSI since getNextSibling() is too slow there
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:59)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitElement(PsiRecursiveElementWalkingVisitor.java:48)
	at org.elixir_lang.dialyzer.inspection.Global$checkFile$1$1$1.visitElement(Global.kt:80)
	at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:51)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitFile(PsiRecursiveElementWalkingVisitor.java:70)
	at com.intellij.psi.impl.compiled.ClsFileImpl.accept(ClsFileImpl.java:412)
	at org.elixir_lang.dialyzer.inspection.Global.checkFile(Global.kt:67)
	at org.elixir_lang.dialyzer.inspection.Global$runInspection$1.visitFile(Global.kt:27)
	at com.intellij.psi.impl.compiled.ClsFileImpl.accept(ClsFileImpl.java:412)
	at com.intellij.analysis.AnalysisScope.doProcessFile(AnalysisScope.java:418)
	at com.intellij.analysis.AnalysisScope.lambda$processFile$10(AnalysisScope.java:367)
	at com.intellij.analysis.AnalysisScope.lambda$commitAndRunInSmartMode$11(AnalysisScope.java:383)
	at com.intellij.psi.impl.PsiDocumentManagerBase.lambda$commitAndRunReadAction$10(PsiDocumentManagerBase.java:522)
	at com.intellij.psi.impl.PsiDocumentManagerBase.lambda$commitAndRunReadAction$11(PsiDocumentManagerBase.java:547)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:873)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitAndRunReadAction(PsiDocumentManagerBase.java:545)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitAndRunReadAction(PsiDocumentManagerBase.java:522)
	at com.intellij.analysis.AnalysisScope.commitAndRunInSmartMode(AnalysisScope.java:381)
	at com.intellij.analysis.AnalysisScope.processFile(AnalysisScope.java:367)
	at com.intellij.analysis.AnalysisScope.lambda$acceptImpl$3(AnalysisScope.java:273)
	at com.intellij.analysis.AnalysisScope.lambda$createScopeIterator$8(AnalysisScope.java:348)
	at com.intellij.openapi.roots.impl.FileIndexBase.lambda$toContentIteratorEx$0(FileIndexBase.java:82)
	at com.intellij.openapi.roots.impl.FileIndexBase$1.visitFileEx(FileIndexBase.java:65)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:295)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:327)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:327)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:327)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:327)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:327)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:327)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:327)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:327)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:327)
	at com.intellij.openapi.roots.impl.FileIndexBase.iterateContentUnderDirectory(FileIndexBase.java:46)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.iterateContentUnderDirectory(ProjectFileIndexImpl.java:35)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.iterateContent(ProjectFileIndexImpl.java:50)
	at com.intellij.openapi.roots.impl.FileIndexBase.iterateContent(FileIndexBase.java:38)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.iterateContent(ProjectFileIndexImpl.java:35)
	at com.intellij.analysis.AnalysisScope.accept(AnalysisScope.java:289)
	at com.intellij.analysis.AnalysisScope.acceptImpl(AnalysisScope.java:267)
	at com.intellij.analysis.AnalysisScope.accept(AnalysisScope.java:251)
	at org.elixir_lang.dialyzer.inspection.Global.runInspection(Global.kt:25)
```

</details>

**Comment by sh41** [comment]
Still live, and there has never been a fix.

`org.elixir_lang.dialyzer.inspection.Global` walks every `PsiFile` the `AnalysisScope` hands it with a `PsiRecursiveElementWalkingVisitor`, with no language, file-type or compiled-PSI check on the way in. When "Analyze" reaches a decompiled `.class`, the platform's `PsiWalkingState` logs the error you saw — and then walks the file anyway, so the cost is a slow traversal as well as a noisy report.

The `language="Elixir"` attribute on the `globalInspection` registration does not prevent this. It reaches a `GlobalInspectionTool` only through a shared *local* inspection tool, which this one does not have; a global tool is handed the whole scope and does its own filtering, and this one does none.

The fix is a guard in `Global.checkFile` skipping any file that is not an `ElixirFile` — dialyzer warnings only ever refer to Elixir source. That also covers decompiled `.beam` files, since `BeamFileImpl` is compiled PSI too. Nothing under `tests/` exercises this inspection today, so it wants a test alongside the guard.

Leaving this open with the diagnosis recorded rather than fixing it now.

This issue was looked at as part of an AI-assisted review of the backlog, and a human checked this reply before it was posted. If any of it is wrong, please say so here.
